### ISSUE TITLE
Training data for UAE-Large-V1

### ISSUE THREAD

**Issue by memray** [SeanLee97/AnglE#15]
Hi,

Awesome work! Can you share the details about what data was used for adapting WhereIsAI/UAE-Large-V1 from BGE-large? Can you share the data as well?

Thanks!

**Comment by SeanLee97** [comment]
Thanks for following our work! 

We're sorry for any inconvenience caused by the fact that we did not publish our training details yet.
Below is the training data that was used for fine-tuning UAE.

![image](https://github.com/SeanLee97/AnglE/assets/12824323/2583e685-8ee2-4bc1-aeca-3822fead4c1a)

We are now working on Next Generation sentence embeddings. After we release our new sentence embedding model, we will open-source our training details for UAE.

**Comment by ozanarmagan** [comment]
@SeanLee97 any updates?
